# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='extension',
            field=models.CharField(default='2211', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='fax_number',
            field=models.CharField(default=2211, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Department'),
        ),
    ]
